lane :launchTest do

  scan(
    project: "FSDropIt.xcodeproj",
    code_coverage: true
  )
  xcov

end

lane :gitDeploy do

  if git_branch() == "master"
    version = get_version_number()
    set_github_release(
      repository_name: "Mrancois/FSDropIt",
      name: "v#{version}",
      tag_name: "v#{version}",
      api_token: ENV["GITHUB_TOKEN"],
      description: changelog_from_git_commits(),
      commitish: "master"
    )

    pod_push()
  end

end
